// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_SLAMD_FLATB_H_
#define FLATBUFFERS_GENERATED_MESSAGES_SLAMD_FLATB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "geometry_generated.h"
#include "primitives_generated.h"
#include "visualizer_generated.h"

namespace slamd {
namespace flatb {

struct UpdateMeshPositions;
struct UpdateMeshPositionsBuilder;

struct UpdateMeshColors;
struct UpdateMeshColorsBuilder;

struct UpdateMeshNormals;
struct UpdateMeshNormalsBuilder;

struct UpdateSpheresPositions;
struct UpdateSpheresPositionsBuilder;

struct UpdateSpheresColors;
struct UpdateSpheresColorsBuilder;

struct UpdateSpheresRadii;
struct UpdateSpheresRadiiBuilder;

struct UpdatePointCloudPositions;
struct UpdatePointCloudPositionsBuilder;

struct UpdatePointCloudColors;
struct UpdatePointCloudColorsBuilder;

struct UpdatePointCloudRadii;
struct UpdatePointCloudRadiiBuilder;

struct SetTransform;
struct SetTransformBuilder;

struct SetObject;
struct SetObjectBuilder;

struct AddGeometry;
struct AddGeometryBuilder;

struct RemoveGeometry;
struct RemoveGeometryBuilder;

struct AddTree;
struct AddTreeBuilder;

struct RemoveTree;
struct RemoveTreeBuilder;

struct ClearPath;
struct ClearPathBuilder;

struct AddView;
struct AddViewBuilder;

struct RemoveView;
struct RemoveViewBuilder;

struct Message;
struct MessageBuilder;

enum MessageUnion : uint8_t {
  MessageUnion_NONE = 0,
  MessageUnion_initial_state = 1,
  MessageUnion_set_transform = 2,
  MessageUnion_set_object = 3,
  MessageUnion_add_geometry = 4,
  MessageUnion_remove_geometry = 5,
  MessageUnion_add_tree = 6,
  MessageUnion_remove_tree = 7,
  MessageUnion_clear_path = 8,
  MessageUnion_add_view = 9,
  MessageUnion_remove_view = 10,
  MessageUnion_update_mesh_positions = 11,
  MessageUnion_update_mesh_colors = 12,
  MessageUnion_update_mesh_normals = 13,
  MessageUnion_update_point_cloud_positions = 14,
  MessageUnion_update_point_cloud_colors = 15,
  MessageUnion_update_point_cloud_radii = 16,
  MessageUnion_update_spheres_positions = 17,
  MessageUnion_update_spheres_colors = 18,
  MessageUnion_update_spheres_radii = 19,
  MessageUnion_MIN = MessageUnion_NONE,
  MessageUnion_MAX = MessageUnion_update_spheres_radii
};

inline const MessageUnion (&EnumValuesMessageUnion())[20] {
  static const MessageUnion values[] = {
    MessageUnion_NONE,
    MessageUnion_initial_state,
    MessageUnion_set_transform,
    MessageUnion_set_object,
    MessageUnion_add_geometry,
    MessageUnion_remove_geometry,
    MessageUnion_add_tree,
    MessageUnion_remove_tree,
    MessageUnion_clear_path,
    MessageUnion_add_view,
    MessageUnion_remove_view,
    MessageUnion_update_mesh_positions,
    MessageUnion_update_mesh_colors,
    MessageUnion_update_mesh_normals,
    MessageUnion_update_point_cloud_positions,
    MessageUnion_update_point_cloud_colors,
    MessageUnion_update_point_cloud_radii,
    MessageUnion_update_spheres_positions,
    MessageUnion_update_spheres_colors,
    MessageUnion_update_spheres_radii
  };
  return values;
}

inline const char * const *EnumNamesMessageUnion() {
  static const char * const names[21] = {
    "NONE",
    "initial_state",
    "set_transform",
    "set_object",
    "add_geometry",
    "remove_geometry",
    "add_tree",
    "remove_tree",
    "clear_path",
    "add_view",
    "remove_view",
    "update_mesh_positions",
    "update_mesh_colors",
    "update_mesh_normals",
    "update_point_cloud_positions",
    "update_point_cloud_colors",
    "update_point_cloud_radii",
    "update_spheres_positions",
    "update_spheres_colors",
    "update_spheres_radii",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageUnion(MessageUnion e) {
  if (::flatbuffers::IsOutRange(e, MessageUnion_NONE, MessageUnion_update_spheres_radii)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageUnion()[index];
}

template<typename T> struct MessageUnionTraits {
  static const MessageUnion enum_value = MessageUnion_NONE;
};

template<> struct MessageUnionTraits<slamd::flatb::InitialState> {
  static const MessageUnion enum_value = MessageUnion_initial_state;
};

template<> struct MessageUnionTraits<slamd::flatb::SetTransform> {
  static const MessageUnion enum_value = MessageUnion_set_transform;
};

template<> struct MessageUnionTraits<slamd::flatb::SetObject> {
  static const MessageUnion enum_value = MessageUnion_set_object;
};

template<> struct MessageUnionTraits<slamd::flatb::AddGeometry> {
  static const MessageUnion enum_value = MessageUnion_add_geometry;
};

template<> struct MessageUnionTraits<slamd::flatb::RemoveGeometry> {
  static const MessageUnion enum_value = MessageUnion_remove_geometry;
};

template<> struct MessageUnionTraits<slamd::flatb::AddTree> {
  static const MessageUnion enum_value = MessageUnion_add_tree;
};

template<> struct MessageUnionTraits<slamd::flatb::RemoveTree> {
  static const MessageUnion enum_value = MessageUnion_remove_tree;
};

template<> struct MessageUnionTraits<slamd::flatb::ClearPath> {
  static const MessageUnion enum_value = MessageUnion_clear_path;
};

template<> struct MessageUnionTraits<slamd::flatb::AddView> {
  static const MessageUnion enum_value = MessageUnion_add_view;
};

template<> struct MessageUnionTraits<slamd::flatb::RemoveView> {
  static const MessageUnion enum_value = MessageUnion_remove_view;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateMeshPositions> {
  static const MessageUnion enum_value = MessageUnion_update_mesh_positions;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateMeshColors> {
  static const MessageUnion enum_value = MessageUnion_update_mesh_colors;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateMeshNormals> {
  static const MessageUnion enum_value = MessageUnion_update_mesh_normals;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdatePointCloudPositions> {
  static const MessageUnion enum_value = MessageUnion_update_point_cloud_positions;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdatePointCloudColors> {
  static const MessageUnion enum_value = MessageUnion_update_point_cloud_colors;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdatePointCloudRadii> {
  static const MessageUnion enum_value = MessageUnion_update_point_cloud_radii;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateSpheresPositions> {
  static const MessageUnion enum_value = MessageUnion_update_spheres_positions;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateSpheresColors> {
  static const MessageUnion enum_value = MessageUnion_update_spheres_colors;
};

template<> struct MessageUnionTraits<slamd::flatb::UpdateSpheresRadii> {
  static const MessageUnion enum_value = MessageUnion_update_spheres_radii;
};

bool VerifyMessageUnion(::flatbuffers::Verifier &verifier, const void *obj, MessageUnion type);
bool VerifyMessageUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct UpdateMeshPositions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateMeshPositionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_POSITIONS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_POSITIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           verifier.EndTable();
  }
};

struct UpdateMeshPositionsBuilder {
  typedef UpdateMeshPositions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateMeshPositions::VT_OBJECT_ID, object_id, 0);
  }
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions) {
    fbb_.AddOffset(UpdateMeshPositions::VT_POSITIONS, positions);
  }
  explicit UpdateMeshPositionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateMeshPositions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateMeshPositions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateMeshPositions> CreateUpdateMeshPositions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions = 0) {
  UpdateMeshPositionsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_positions(positions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateMeshPositions> CreateUpdateMeshPositionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *positions = nullptr) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*positions) : 0;
  return slamd::flatb::CreateUpdateMeshPositions(
      _fbb,
      object_id,
      positions__);
}

struct UpdateMeshColors FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateMeshColorsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_COLORS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_COLORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           verifier.EndTable();
  }
};

struct UpdateMeshColorsBuilder {
  typedef UpdateMeshColors Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateMeshColors::VT_OBJECT_ID, object_id, 0);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors) {
    fbb_.AddOffset(UpdateMeshColors::VT_COLORS, colors);
  }
  explicit UpdateMeshColorsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateMeshColors> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateMeshColors>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateMeshColors> CreateUpdateMeshColors(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors = 0) {
  UpdateMeshColorsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_colors(colors);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateMeshColors> CreateUpdateMeshColorsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *colors = nullptr) {
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*colors) : 0;
  return slamd::flatb::CreateUpdateMeshColors(
      _fbb,
      object_id,
      colors__);
}

struct UpdateMeshNormals FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateMeshNormalsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_NORMALS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *normals() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_NORMALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_NORMALS) &&
           verifier.VerifyVector(normals()) &&
           verifier.EndTable();
  }
};

struct UpdateMeshNormalsBuilder {
  typedef UpdateMeshNormals Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateMeshNormals::VT_OBJECT_ID, object_id, 0);
  }
  void add_normals(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> normals) {
    fbb_.AddOffset(UpdateMeshNormals::VT_NORMALS, normals);
  }
  explicit UpdateMeshNormalsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateMeshNormals> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateMeshNormals>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateMeshNormals> CreateUpdateMeshNormals(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> normals = 0) {
  UpdateMeshNormalsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_normals(normals);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateMeshNormals> CreateUpdateMeshNormalsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *normals = nullptr) {
  auto normals__ = normals ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*normals) : 0;
  return slamd::flatb::CreateUpdateMeshNormals(
      _fbb,
      object_id,
      normals__);
}

struct UpdateSpheresPositions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateSpheresPositionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_POSITIONS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_POSITIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           verifier.EndTable();
  }
};

struct UpdateSpheresPositionsBuilder {
  typedef UpdateSpheresPositions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateSpheresPositions::VT_OBJECT_ID, object_id, 0);
  }
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions) {
    fbb_.AddOffset(UpdateSpheresPositions::VT_POSITIONS, positions);
  }
  explicit UpdateSpheresPositionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateSpheresPositions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateSpheresPositions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateSpheresPositions> CreateUpdateSpheresPositions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions = 0) {
  UpdateSpheresPositionsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_positions(positions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateSpheresPositions> CreateUpdateSpheresPositionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *positions = nullptr) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*positions) : 0;
  return slamd::flatb::CreateUpdateSpheresPositions(
      _fbb,
      object_id,
      positions__);
}

struct UpdateSpheresColors FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateSpheresColorsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_COLORS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_COLORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           verifier.EndTable();
  }
};

struct UpdateSpheresColorsBuilder {
  typedef UpdateSpheresColors Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateSpheresColors::VT_OBJECT_ID, object_id, 0);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors) {
    fbb_.AddOffset(UpdateSpheresColors::VT_COLORS, colors);
  }
  explicit UpdateSpheresColorsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateSpheresColors> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateSpheresColors>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateSpheresColors> CreateUpdateSpheresColors(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors = 0) {
  UpdateSpheresColorsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_colors(colors);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateSpheresColors> CreateUpdateSpheresColorsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *colors = nullptr) {
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*colors) : 0;
  return slamd::flatb::CreateUpdateSpheresColors(
      _fbb,
      object_id,
      colors__);
}

struct UpdateSpheresRadii FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateSpheresRadiiBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_RADII = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<float> *radii() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RADII);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_RADII) &&
           verifier.VerifyVector(radii()) &&
           verifier.EndTable();
  }
};

struct UpdateSpheresRadiiBuilder {
  typedef UpdateSpheresRadii Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdateSpheresRadii::VT_OBJECT_ID, object_id, 0);
  }
  void add_radii(::flatbuffers::Offset<::flatbuffers::Vector<float>> radii) {
    fbb_.AddOffset(UpdateSpheresRadii::VT_RADII, radii);
  }
  explicit UpdateSpheresRadiiBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateSpheresRadii> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateSpheresRadii>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateSpheresRadii> CreateUpdateSpheresRadii(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> radii = 0) {
  UpdateSpheresRadiiBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_radii(radii);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateSpheresRadii> CreateUpdateSpheresRadiiDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<float> *radii = nullptr) {
  auto radii__ = radii ? _fbb.CreateVector<float>(*radii) : 0;
  return slamd::flatb::CreateUpdateSpheresRadii(
      _fbb,
      object_id,
      radii__);
}

struct UpdatePointCloudPositions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdatePointCloudPositionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_POSITIONS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_POSITIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           verifier.EndTable();
  }
};

struct UpdatePointCloudPositionsBuilder {
  typedef UpdatePointCloudPositions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdatePointCloudPositions::VT_OBJECT_ID, object_id, 0);
  }
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions) {
    fbb_.AddOffset(UpdatePointCloudPositions::VT_POSITIONS, positions);
  }
  explicit UpdatePointCloudPositionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdatePointCloudPositions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdatePointCloudPositions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdatePointCloudPositions> CreateUpdatePointCloudPositions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions = 0) {
  UpdatePointCloudPositionsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_positions(positions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdatePointCloudPositions> CreateUpdatePointCloudPositionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *positions = nullptr) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*positions) : 0;
  return slamd::flatb::CreateUpdatePointCloudPositions(
      _fbb,
      object_id,
      positions__);
}

struct UpdatePointCloudColors FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdatePointCloudColorsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_COLORS = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_COLORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           verifier.EndTable();
  }
};

struct UpdatePointCloudColorsBuilder {
  typedef UpdatePointCloudColors Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdatePointCloudColors::VT_OBJECT_ID, object_id, 0);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors) {
    fbb_.AddOffset(UpdatePointCloudColors::VT_COLORS, colors);
  }
  explicit UpdatePointCloudColorsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdatePointCloudColors> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdatePointCloudColors>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdatePointCloudColors> CreateUpdatePointCloudColors(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors = 0) {
  UpdatePointCloudColorsBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_colors(colors);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdatePointCloudColors> CreateUpdatePointCloudColorsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<slamd::flatb::Vec3> *colors = nullptr) {
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*colors) : 0;
  return slamd::flatb::CreateUpdatePointCloudColors(
      _fbb,
      object_id,
      colors__);
}

struct UpdatePointCloudRadii FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdatePointCloudRadiiBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_RADII = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  const ::flatbuffers::Vector<float> *radii() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RADII);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyOffset(verifier, VT_RADII) &&
           verifier.VerifyVector(radii()) &&
           verifier.EndTable();
  }
};

struct UpdatePointCloudRadiiBuilder {
  typedef UpdatePointCloudRadii Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(UpdatePointCloudRadii::VT_OBJECT_ID, object_id, 0);
  }
  void add_radii(::flatbuffers::Offset<::flatbuffers::Vector<float>> radii) {
    fbb_.AddOffset(UpdatePointCloudRadii::VT_RADII, radii);
  }
  explicit UpdatePointCloudRadiiBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdatePointCloudRadii> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdatePointCloudRadii>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdatePointCloudRadii> CreateUpdatePointCloudRadii(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> radii = 0) {
  UpdatePointCloudRadiiBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_radii(radii);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdatePointCloudRadii> CreateUpdatePointCloudRadiiDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    const std::vector<float> *radii = nullptr) {
  auto radii__ = radii ? _fbb.CreateVector<float>(*radii) : 0;
  return slamd::flatb::CreateUpdatePointCloudRadii(
      _fbb,
      object_id,
      radii__);
}

struct SetTransform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetTransformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREE_ID = 4,
    VT_TREE_PATH = 6,
    VT_TRANSFORM = 8
  };
  uint64_t tree_id() const {
    return GetField<uint64_t>(VT_TREE_ID, 0);
  }
  const ::flatbuffers::String *tree_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TREE_PATH);
  }
  const slamd::flatb::Mat4 *transform() const {
    return GetStruct<const slamd::flatb::Mat4 *>(VT_TRANSFORM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TREE_ID, 8) &&
           VerifyOffset(verifier, VT_TREE_PATH) &&
           verifier.VerifyString(tree_path()) &&
           VerifyField<slamd::flatb::Mat4>(verifier, VT_TRANSFORM, 4) &&
           verifier.EndTable();
  }
};

struct SetTransformBuilder {
  typedef SetTransform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tree_id(uint64_t tree_id) {
    fbb_.AddElement<uint64_t>(SetTransform::VT_TREE_ID, tree_id, 0);
  }
  void add_tree_path(::flatbuffers::Offset<::flatbuffers::String> tree_path) {
    fbb_.AddOffset(SetTransform::VT_TREE_PATH, tree_path);
  }
  void add_transform(const slamd::flatb::Mat4 *transform) {
    fbb_.AddStruct(SetTransform::VT_TRANSFORM, transform);
  }
  explicit SetTransformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetTransform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetTransform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetTransform> CreateSetTransform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tree_path = 0,
    const slamd::flatb::Mat4 *transform = nullptr) {
  SetTransformBuilder builder_(_fbb);
  builder_.add_tree_id(tree_id);
  builder_.add_transform(transform);
  builder_.add_tree_path(tree_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetTransform> CreateSetTransformDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    const char *tree_path = nullptr,
    const slamd::flatb::Mat4 *transform = nullptr) {
  auto tree_path__ = tree_path ? _fbb.CreateString(tree_path) : 0;
  return slamd::flatb::CreateSetTransform(
      _fbb,
      tree_id,
      tree_path__,
      transform);
}

struct SetObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREE_ID = 4,
    VT_TREE_PATH = 6,
    VT_GEOMETRY_ID = 8
  };
  uint64_t tree_id() const {
    return GetField<uint64_t>(VT_TREE_ID, 0);
  }
  const ::flatbuffers::String *tree_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TREE_PATH);
  }
  uint64_t geometry_id() const {
    return GetField<uint64_t>(VT_GEOMETRY_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TREE_ID, 8) &&
           VerifyOffset(verifier, VT_TREE_PATH) &&
           verifier.VerifyString(tree_path()) &&
           VerifyField<uint64_t>(verifier, VT_GEOMETRY_ID, 8) &&
           verifier.EndTable();
  }
};

struct SetObjectBuilder {
  typedef SetObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tree_id(uint64_t tree_id) {
    fbb_.AddElement<uint64_t>(SetObject::VT_TREE_ID, tree_id, 0);
  }
  void add_tree_path(::flatbuffers::Offset<::flatbuffers::String> tree_path) {
    fbb_.AddOffset(SetObject::VT_TREE_PATH, tree_path);
  }
  void add_geometry_id(uint64_t geometry_id) {
    fbb_.AddElement<uint64_t>(SetObject::VT_GEOMETRY_ID, geometry_id, 0);
  }
  explicit SetObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetObject> CreateSetObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tree_path = 0,
    uint64_t geometry_id = 0) {
  SetObjectBuilder builder_(_fbb);
  builder_.add_geometry_id(geometry_id);
  builder_.add_tree_id(tree_id);
  builder_.add_tree_path(tree_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetObject> CreateSetObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    const char *tree_path = nullptr,
    uint64_t geometry_id = 0) {
  auto tree_path__ = tree_path ? _fbb.CreateString(tree_path) : 0;
  return slamd::flatb::CreateSetObject(
      _fbb,
      tree_id,
      tree_path__,
      geometry_id);
}

struct AddGeometry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddGeometryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GEOMETRY = 4
  };
  const slamd::flatb::Geometry *geometry() const {
    return GetPointer<const slamd::flatb::Geometry *>(VT_GEOMETRY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GEOMETRY) &&
           verifier.VerifyTable(geometry()) &&
           verifier.EndTable();
  }
};

struct AddGeometryBuilder {
  typedef AddGeometry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_geometry(::flatbuffers::Offset<slamd::flatb::Geometry> geometry) {
    fbb_.AddOffset(AddGeometry::VT_GEOMETRY, geometry);
  }
  explicit AddGeometryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddGeometry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddGeometry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddGeometry> CreateAddGeometry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slamd::flatb::Geometry> geometry = 0) {
  AddGeometryBuilder builder_(_fbb);
  builder_.add_geometry(geometry);
  return builder_.Finish();
}

struct RemoveGeometry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveGeometryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GEOMETRY_ID = 4
  };
  uint64_t geometry_id() const {
    return GetField<uint64_t>(VT_GEOMETRY_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_GEOMETRY_ID, 8) &&
           verifier.EndTable();
  }
};

struct RemoveGeometryBuilder {
  typedef RemoveGeometry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_geometry_id(uint64_t geometry_id) {
    fbb_.AddElement<uint64_t>(RemoveGeometry::VT_GEOMETRY_ID, geometry_id, 0);
  }
  explicit RemoveGeometryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveGeometry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveGeometry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveGeometry> CreateRemoveGeometry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t geometry_id = 0) {
  RemoveGeometryBuilder builder_(_fbb);
  builder_.add_geometry_id(geometry_id);
  return builder_.Finish();
}

struct AddTree FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddTreeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREE = 4
  };
  const slamd::flatb::Tree *tree() const {
    return GetPointer<const slamd::flatb::Tree *>(VT_TREE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TREE) &&
           verifier.VerifyTable(tree()) &&
           verifier.EndTable();
  }
};

struct AddTreeBuilder {
  typedef AddTree Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tree(::flatbuffers::Offset<slamd::flatb::Tree> tree) {
    fbb_.AddOffset(AddTree::VT_TREE, tree);
  }
  explicit AddTreeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddTree> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddTree>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddTree> CreateAddTree(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slamd::flatb::Tree> tree = 0) {
  AddTreeBuilder builder_(_fbb);
  builder_.add_tree(tree);
  return builder_.Finish();
}

struct RemoveTree FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveTreeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREE_ID = 4
  };
  uint64_t tree_id() const {
    return GetField<uint64_t>(VT_TREE_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TREE_ID, 8) &&
           verifier.EndTable();
  }
};

struct RemoveTreeBuilder {
  typedef RemoveTree Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tree_id(uint64_t tree_id) {
    fbb_.AddElement<uint64_t>(RemoveTree::VT_TREE_ID, tree_id, 0);
  }
  explicit RemoveTreeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveTree> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveTree>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveTree> CreateRemoveTree(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0) {
  RemoveTreeBuilder builder_(_fbb);
  builder_.add_tree_id(tree_id);
  return builder_.Finish();
}

struct ClearPath FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClearPathBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREE_ID = 4,
    VT_TREE_PATH = 6
  };
  uint64_t tree_id() const {
    return GetField<uint64_t>(VT_TREE_ID, 0);
  }
  const ::flatbuffers::String *tree_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TREE_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TREE_ID, 8) &&
           VerifyOffset(verifier, VT_TREE_PATH) &&
           verifier.VerifyString(tree_path()) &&
           verifier.EndTable();
  }
};

struct ClearPathBuilder {
  typedef ClearPath Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tree_id(uint64_t tree_id) {
    fbb_.AddElement<uint64_t>(ClearPath::VT_TREE_ID, tree_id, 0);
  }
  void add_tree_path(::flatbuffers::Offset<::flatbuffers::String> tree_path) {
    fbb_.AddOffset(ClearPath::VT_TREE_PATH, tree_path);
  }
  explicit ClearPathBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClearPath> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClearPath>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClearPath> CreateClearPath(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tree_path = 0) {
  ClearPathBuilder builder_(_fbb);
  builder_.add_tree_id(tree_id);
  builder_.add_tree_path(tree_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClearPath> CreateClearPathDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tree_id = 0,
    const char *tree_path = nullptr) {
  auto tree_path__ = tree_path ? _fbb.CreateString(tree_path) : 0;
  return slamd::flatb::CreateClearPath(
      _fbb,
      tree_id,
      tree_path__);
}

struct AddView FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddViewBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIEW = 4
  };
  const slamd::flatb::View *view() const {
    return GetPointer<const slamd::flatb::View *>(VT_VIEW);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIEW) &&
           verifier.VerifyTable(view()) &&
           verifier.EndTable();
  }
};

struct AddViewBuilder {
  typedef AddView Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_view(::flatbuffers::Offset<slamd::flatb::View> view) {
    fbb_.AddOffset(AddView::VT_VIEW, view);
  }
  explicit AddViewBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddView> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddView>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddView> CreateAddView(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slamd::flatb::View> view = 0) {
  AddViewBuilder builder_(_fbb);
  builder_.add_view(view);
  return builder_.Finish();
}

struct RemoveView FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveViewBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct RemoveViewBuilder {
  typedef RemoveView Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(RemoveView::VT_NAME, name);
  }
  explicit RemoveViewBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveView> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveView>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveView> CreateRemoveView(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  RemoveViewBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RemoveView> CreateRemoveViewDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slamd::flatb::CreateRemoveView(
      _fbb,
      name__);
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_MESSAGE = 6
  };
  slamd::flatb::MessageUnion message_type() const {
    return static_cast<slamd::flatb::MessageUnion>(GetField<uint8_t>(VT_MESSAGE_TYPE, 0));
  }
  const void *message() const {
    return GetPointer<const void *>(VT_MESSAGE);
  }
  template<typename T> const T *message_as() const;
  const slamd::flatb::InitialState *message_as_initial_state() const {
    return message_type() == slamd::flatb::MessageUnion_initial_state ? static_cast<const slamd::flatb::InitialState *>(message()) : nullptr;
  }
  const slamd::flatb::SetTransform *message_as_set_transform() const {
    return message_type() == slamd::flatb::MessageUnion_set_transform ? static_cast<const slamd::flatb::SetTransform *>(message()) : nullptr;
  }
  const slamd::flatb::SetObject *message_as_set_object() const {
    return message_type() == slamd::flatb::MessageUnion_set_object ? static_cast<const slamd::flatb::SetObject *>(message()) : nullptr;
  }
  const slamd::flatb::AddGeometry *message_as_add_geometry() const {
    return message_type() == slamd::flatb::MessageUnion_add_geometry ? static_cast<const slamd::flatb::AddGeometry *>(message()) : nullptr;
  }
  const slamd::flatb::RemoveGeometry *message_as_remove_geometry() const {
    return message_type() == slamd::flatb::MessageUnion_remove_geometry ? static_cast<const slamd::flatb::RemoveGeometry *>(message()) : nullptr;
  }
  const slamd::flatb::AddTree *message_as_add_tree() const {
    return message_type() == slamd::flatb::MessageUnion_add_tree ? static_cast<const slamd::flatb::AddTree *>(message()) : nullptr;
  }
  const slamd::flatb::RemoveTree *message_as_remove_tree() const {
    return message_type() == slamd::flatb::MessageUnion_remove_tree ? static_cast<const slamd::flatb::RemoveTree *>(message()) : nullptr;
  }
  const slamd::flatb::ClearPath *message_as_clear_path() const {
    return message_type() == slamd::flatb::MessageUnion_clear_path ? static_cast<const slamd::flatb::ClearPath *>(message()) : nullptr;
  }
  const slamd::flatb::AddView *message_as_add_view() const {
    return message_type() == slamd::flatb::MessageUnion_add_view ? static_cast<const slamd::flatb::AddView *>(message()) : nullptr;
  }
  const slamd::flatb::RemoveView *message_as_remove_view() const {
    return message_type() == slamd::flatb::MessageUnion_remove_view ? static_cast<const slamd::flatb::RemoveView *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateMeshPositions *message_as_update_mesh_positions() const {
    return message_type() == slamd::flatb::MessageUnion_update_mesh_positions ? static_cast<const slamd::flatb::UpdateMeshPositions *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateMeshColors *message_as_update_mesh_colors() const {
    return message_type() == slamd::flatb::MessageUnion_update_mesh_colors ? static_cast<const slamd::flatb::UpdateMeshColors *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateMeshNormals *message_as_update_mesh_normals() const {
    return message_type() == slamd::flatb::MessageUnion_update_mesh_normals ? static_cast<const slamd::flatb::UpdateMeshNormals *>(message()) : nullptr;
  }
  const slamd::flatb::UpdatePointCloudPositions *message_as_update_point_cloud_positions() const {
    return message_type() == slamd::flatb::MessageUnion_update_point_cloud_positions ? static_cast<const slamd::flatb::UpdatePointCloudPositions *>(message()) : nullptr;
  }
  const slamd::flatb::UpdatePointCloudColors *message_as_update_point_cloud_colors() const {
    return message_type() == slamd::flatb::MessageUnion_update_point_cloud_colors ? static_cast<const slamd::flatb::UpdatePointCloudColors *>(message()) : nullptr;
  }
  const slamd::flatb::UpdatePointCloudRadii *message_as_update_point_cloud_radii() const {
    return message_type() == slamd::flatb::MessageUnion_update_point_cloud_radii ? static_cast<const slamd::flatb::UpdatePointCloudRadii *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateSpheresPositions *message_as_update_spheres_positions() const {
    return message_type() == slamd::flatb::MessageUnion_update_spheres_positions ? static_cast<const slamd::flatb::UpdateSpheresPositions *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateSpheresColors *message_as_update_spheres_colors() const {
    return message_type() == slamd::flatb::MessageUnion_update_spheres_colors ? static_cast<const slamd::flatb::UpdateSpheresColors *>(message()) : nullptr;
  }
  const slamd::flatb::UpdateSpheresRadii *message_as_update_spheres_radii() const {
    return message_type() == slamd::flatb::MessageUnion_update_spheres_radii ? static_cast<const slamd::flatb::UpdateSpheresRadii *>(message()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MESSAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           VerifyMessageUnion(verifier, message(), message_type()) &&
           verifier.EndTable();
  }
};

template<> inline const slamd::flatb::InitialState *Message::message_as<slamd::flatb::InitialState>() const {
  return message_as_initial_state();
}

template<> inline const slamd::flatb::SetTransform *Message::message_as<slamd::flatb::SetTransform>() const {
  return message_as_set_transform();
}

template<> inline const slamd::flatb::SetObject *Message::message_as<slamd::flatb::SetObject>() const {
  return message_as_set_object();
}

template<> inline const slamd::flatb::AddGeometry *Message::message_as<slamd::flatb::AddGeometry>() const {
  return message_as_add_geometry();
}

template<> inline const slamd::flatb::RemoveGeometry *Message::message_as<slamd::flatb::RemoveGeometry>() const {
  return message_as_remove_geometry();
}

template<> inline const slamd::flatb::AddTree *Message::message_as<slamd::flatb::AddTree>() const {
  return message_as_add_tree();
}

template<> inline const slamd::flatb::RemoveTree *Message::message_as<slamd::flatb::RemoveTree>() const {
  return message_as_remove_tree();
}

template<> inline const slamd::flatb::ClearPath *Message::message_as<slamd::flatb::ClearPath>() const {
  return message_as_clear_path();
}

template<> inline const slamd::flatb::AddView *Message::message_as<slamd::flatb::AddView>() const {
  return message_as_add_view();
}

template<> inline const slamd::flatb::RemoveView *Message::message_as<slamd::flatb::RemoveView>() const {
  return message_as_remove_view();
}

template<> inline const slamd::flatb::UpdateMeshPositions *Message::message_as<slamd::flatb::UpdateMeshPositions>() const {
  return message_as_update_mesh_positions();
}

template<> inline const slamd::flatb::UpdateMeshColors *Message::message_as<slamd::flatb::UpdateMeshColors>() const {
  return message_as_update_mesh_colors();
}

template<> inline const slamd::flatb::UpdateMeshNormals *Message::message_as<slamd::flatb::UpdateMeshNormals>() const {
  return message_as_update_mesh_normals();
}

template<> inline const slamd::flatb::UpdatePointCloudPositions *Message::message_as<slamd::flatb::UpdatePointCloudPositions>() const {
  return message_as_update_point_cloud_positions();
}

template<> inline const slamd::flatb::UpdatePointCloudColors *Message::message_as<slamd::flatb::UpdatePointCloudColors>() const {
  return message_as_update_point_cloud_colors();
}

template<> inline const slamd::flatb::UpdatePointCloudRadii *Message::message_as<slamd::flatb::UpdatePointCloudRadii>() const {
  return message_as_update_point_cloud_radii();
}

template<> inline const slamd::flatb::UpdateSpheresPositions *Message::message_as<slamd::flatb::UpdateSpheresPositions>() const {
  return message_as_update_spheres_positions();
}

template<> inline const slamd::flatb::UpdateSpheresColors *Message::message_as<slamd::flatb::UpdateSpheresColors>() const {
  return message_as_update_spheres_colors();
}

template<> inline const slamd::flatb::UpdateSpheresRadii *Message::message_as<slamd::flatb::UpdateSpheresRadii>() const {
  return message_as_update_spheres_radii();
}

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(slamd::flatb::MessageUnion message_type) {
    fbb_.AddElement<uint8_t>(Message::VT_MESSAGE_TYPE, static_cast<uint8_t>(message_type), 0);
  }
  void add_message(::flatbuffers::Offset<void> message) {
    fbb_.AddOffset(Message::VT_MESSAGE, message);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    slamd::flatb::MessageUnion message_type = slamd::flatb::MessageUnion_NONE,
    ::flatbuffers::Offset<void> message = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_message_type(message_type);
  return builder_.Finish();
}

inline bool VerifyMessageUnion(::flatbuffers::Verifier &verifier, const void *obj, MessageUnion type) {
  switch (type) {
    case MessageUnion_NONE: {
      return true;
    }
    case MessageUnion_initial_state: {
      auto ptr = reinterpret_cast<const slamd::flatb::InitialState *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_set_transform: {
      auto ptr = reinterpret_cast<const slamd::flatb::SetTransform *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_set_object: {
      auto ptr = reinterpret_cast<const slamd::flatb::SetObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_add_geometry: {
      auto ptr = reinterpret_cast<const slamd::flatb::AddGeometry *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_remove_geometry: {
      auto ptr = reinterpret_cast<const slamd::flatb::RemoveGeometry *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_add_tree: {
      auto ptr = reinterpret_cast<const slamd::flatb::AddTree *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_remove_tree: {
      auto ptr = reinterpret_cast<const slamd::flatb::RemoveTree *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_clear_path: {
      auto ptr = reinterpret_cast<const slamd::flatb::ClearPath *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_add_view: {
      auto ptr = reinterpret_cast<const slamd::flatb::AddView *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_remove_view: {
      auto ptr = reinterpret_cast<const slamd::flatb::RemoveView *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_mesh_positions: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateMeshPositions *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_mesh_colors: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateMeshColors *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_mesh_normals: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateMeshNormals *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_point_cloud_positions: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdatePointCloudPositions *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_point_cloud_colors: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdatePointCloudColors *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_point_cloud_radii: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdatePointCloudRadii *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_spheres_positions: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateSpheresPositions *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_spheres_colors: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateSpheresColors *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageUnion_update_spheres_radii: {
      auto ptr = reinterpret_cast<const slamd::flatb::UpdateSpheresRadii *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMessageUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessageUnion(
        verifier,  values->Get(i), types->GetEnum<MessageUnion>(i))) {
      return false;
    }
  }
  return true;
}

inline const slamd::flatb::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<slamd::flatb::Message>(buf);
}

inline const slamd::flatb::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<slamd::flatb::Message>(buf);
}

inline bool VerifyMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<slamd::flatb::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<slamd::flatb::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slamd::flatb::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slamd::flatb::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace flatb
}  // namespace slamd

#endif  // FLATBUFFERS_GENERATED_MESSAGES_SLAMD_FLATB_H_
