"""
SlamDunk visualization library
"""
from __future__ import annotations
import numpy
import typing
from . import _geom
from . import geom
__all__: list[str] = ['Scene', 'Visualizer', 'geom', 'spawn_window']
class Scene:
    def __init__(self) -> None:
        ...
    def clear(self, path: str) -> None:
        ...
    def set_object(self, path: str, object: ...) -> None:
        ...
    def set_transform(self, path: str, transform: numpy.ndarray) -> None:
        ...
class Visualizer:
    def __init__(self, name: str, port: typing.SupportsInt | typing.SupportsIndex = 5555) -> None:
        ...
    def add_scene(self, name: str, scene: Scene) -> None:
        ...
    def delete_scene(self, arg0: str) -> None:
        ...
    def scene(self, name: str) -> Scene:
        ...
def spawn_window(port: typing.SupportsInt | typing.SupportsIndex = 5555, executable_path: str | None = None) -> None:
    ...
